# Generated by Django 5.0.1 on 2024-01-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_cartitem_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
