# Generated by Django 5.0.1 on 2024-01-16 09:03

import django.db.models.deletion
import store_management.views
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUpdateView',
            fields=[
                ('seller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store_management.seller')),
            ],
            bases=('store_management.seller', store_management.views.ProductOwnerTest, store_management.views.MyBaseUpdate),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EditElectroProduct',
            fields=[
                ('myupdateview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store_management.myupdateview')),
            ],
            bases=('store_management.myupdateview',),
        ),
        migrations.CreateModel(
            name='EditFoodProduct',
            fields=[
                ('myupdateview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store_management.myupdateview')),
            ],
            bases=('store_management.myupdateview',),
        ),
        migrations.CreateModel(
            name='EditForniProduct',
            fields=[
                ('myupdateview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store_management.myupdateview')),
            ],
            bases=('store_management.myupdateview',),
        ),
    ]
