# Generated by Django 5.0.1 on 2024-01-30 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_myupdateview_alter_seller_store_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='added_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='n_votes',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='votes recived can not be lower than 0')]),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='total_score',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='total score can not be lower than 0')]),
        ),
    ]
